name: Sync Backend

on:
  workflow_dispatch:
  push:
    paths:
    - 'backend/**'

jobs:
  sync:
    runs-on: rs-1

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Deploy with rsync
      run: rsync -avz --delete backend/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/lib/pterodactyl/volumes/517bbc7b-244f-4df8-b5fb-61a61026925a/
